export const doctors = [
  {
    id: 101,
    name: "Nurse Amina Khalid",
    email: "amina.khalid@clinic.pk",
    specialization: "Neonatal Nurse",
    clinic_name: "Mother Care Hospital",
    location: "Islamabad",
    contact: "+92 300 1112233",
    experience: "6 years",
    department: "BSN",
    qualification: "BSN, RN",
    available_time: "Mon‑Fri, 8AM‑2PM",
    about: "Specializes in neonatal intensive care for newborns.",
    image: "https://images.pexels.com/photos/5207117/pexels-photo-5207117.jpeg",
    job: "Senior Neonatal Nurse"
  },

  {
    id: 102,
    name: "Nurse Faiza Shah",
    email: "faiza.shah@clinic.pk",
    specialization: "Critical Care Nurse",
    clinic_name: "City General Hospital",
    location: "Lahore",
    contact: "+92 333 2233445",
    experience: "9 years",
    department: "BSN",
    qualification: "BSN, CCRN",
    available_time: "Mon‑Sat, 10AM‑6PM",
    about: "Works in ICU and emergency care units.",
    image: "https://images.pexels.com/photos/19177022/pexels-photo-19177022.jpeg",
    job: "ICU Supervisor"
  },
  {
    id: 103,
    name: "Nurse Zara Qureshi",
    email: "zara.q@clinic.pk",
    specialization: "Geriatric Nurse",
    clinic_name: "Sunrise Elderly Care",
    location: "Karachi",
    contact: "+92 301 4455667",
    experience: "11 years",
    department: "BSN",
    qualification: "BSN, RN",
    available_time: "Mon‑Fri, 9AM‑3PM",
    about: "Provides care for elderly patients in long‑term facilities.",
    image: "https://images.pexels.com/photos/5234517/pexels-photo-5234517.jpeg",
    job: "Geriatric Specialist"
  },
  {
    id: 104,
    name: "Nurse Areeba Iqbal",
    email: "areeba.iqbal@clinic.pk",
    specialization: "Pediatric Nurse",
    clinic_name: "Children's Health Clinic",
    location: "Multan",
    contact: "+92 321 9988776",
    experience: "7 years",
    department: "BSN",
    qualification: "BSN, CPN",
    available_time: "Mon‑Sat, 9AM‑1PM",
    about: "Dedicated to pediatric care and family support.",
    image: "https://images.pexels.com/photos/5998482/pexels-photo-5998482.jpeg",
    job: "Lead Pediatric Nurse"
  },
  {
    id: 105,
    name: "Nurse  kamran Tariq",
    email: "samina.tariq@clinic.pk",
    specialization: "Community Health Nurse",
    clinic_name: "Rural Health Center",
    location: "Bahawalpur",
    contact: "+92 302 3456789",
    experience: "10 years",
    department: "BSN",
    qualification: "BSN, CHN",
    available_time: "Mon‑Fri, 8AM‑1PM",
    about: "Serves rural communities with health education programs.",
    image: "https://images.pexels.com/photos/8460157/pexels-photo-8460157.jpeg"
  },
  {
    id: 106,
    name: "Nurse  Umer Naveed",
    email: "hira.naveed@clinic.pk",
    specialization: "Oncology Nurse",
    clinic_name: "Cancer Care Unit",
    location: "Islamabad",
    contact: "+92 311 5566778",
    experience: "8 years",
    department: "BSN",
    qualification: "BSN, OCN",
    available_time: "Mon‑Sat, 9AM‑5PM",
    about: "Provides chemotherapy support and cancer patient education.",
    image: "https://images.pexels.com/photos/14438788/pexels-photo-14438788.jpeg",
    job: "Oncology Nurse Specialist"
  },
  {
    id: 107,
    name: "Nurse  Bilal Ahmed",
    email: "zahra.ahmed@clinic.pk",
    specialization: "Psychiatric Nurse",
    clinic_name: "Mental Health Clinic",
    location: "Karachi",
    contact: "+92 305 7788990",
    experience: "12 years",
    department: "BSN",
    qualification: "BSN, PMHN",
    available_time: "Mon‑Fri, 10AM‑4PM",
    about: "Works with patients dealing with mental health issues.",
    image: "https://images.pexels.com/photos/5452200/pexels-photo-5452200.jpeg",
    job: "Lead Psychiatric Nurse"
  },
  {
    id: 108,
    name: "Nurse  Ahmad Ijaz",
    email: "kiran.ijaz@clinic.pk",
    specialization: "Cardiac Care Nurse",
    clinic_name: "Heart Institute",
    location: "Lahore",
    contact: "+92 300 8899001",
    experience: "9 years",
    department: "BSN",
    qualification: "BSN, RN",
    available_time: "Mon‑Sat, 8AM‑2PM",
    about: "Assists cardiologists in managing heart disease patients.",
    image: "https://images.pexels.com/photos/7108250/pexels-photo-7108250.jpeg",
    job: "Cardiac Nurse Coordinator"
  },
  {
    id: 109,
    name: "Nurse Fahad Farooq",
    email: "maha.farooq@clinic.pk",
    specialization: "Obstetric Nurse",
    clinic_name: "Women Care Hospital",
    location: "Multan",
    contact: "+92 301 1122334",
    experience: "7 years",
    department: "BSN",
    qualification: "BSN, RN",
    available_time: "Mon‑Fri, 9AM‑3PM",
    about: "Supports labor, delivery, and postpartum care.",
    image: "https://images.pexels.com/photos/8326324/pexels-photo-8326324.jpeg",
    job: "OB Nurse"
  },
  {
    id: 110,
    name: "Nurse  Raza Javed",
    email: "raza.javed@clinic.pk",
    specialization: "Dialysis Nurse",
    clinic_name: "Kidney Center",
    location: "Quetta",
    contact: "+92 333 3344455",
    experience: "6 years",
    department: "BSN",
    qualification: "BSN, RN",
    available_time: "Mon‑Sat, 7AM‑1PM",
    about: "Manages dialysis treatments for kidney patients.",
    image: "https://images.pexels.com/photos/26886760/pexels-photo-26886760.jpeg",
    job: "Dialysis Nurse"
  },
  {
    id: 111,
    name: "Nurse Wardha Zafar",
    email: "wardha.zafar@clinic.pk",
    specialization: "Orthopedic Nurse",
    clinic_name: "Bone & Joint Center",
    location: "Peshawar",
    contact: "+92 311 2233445",
    experience: "8 years",
    department: "BSN",
    qualification: "BSN, ONC",
    available_time: "Mon‑Fri, 8AM‑4PM",
    about: "Assists patients after orthopedic surgery.",
    image: "https://plus.unsplash.com/premium_photo-1681967035389-84aabd80cb1e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDJ8fHxlbnwwfHx8fHw%3D",
    job: "Ortho Staff Nurse"
  },
  {
    id: 112,
    name: "Nurse Rabia Saeed",
    email: "rabia.saeed@clinic.pk",
    specialization: "Nephrology Nurse",
    clinic_name: "Kidney Clinic",
    location: "Faisalabad",
    contact: "+92 312 4455667",
    experience: "10 years",
    department: "BSN",
    qualification: "BSN, RN",
    available_time: "Mon‑Sat, 8AM‑2PM",
    about: "Provides care for patients undergoing dialysis or transplants.",
    image: "/imagesBsn/bsn2.jpg",
    job: "Nephrology Nurse"
  },
  {
    id: 113,
    name: "Nurse Nimra Ashraf",
    email: "nimra.ashraf@clinic.pk",
    specialization: "Palliative Care Nurse",
    clinic_name: "Hospice Center",
    location: "Islamabad",
    contact: "+92 300 5556677",
    experience: "9 years",
    department: "BSN",
    qualification: "BSN, CHPN",
    available_time: "Mon‑Fri, 9AM‑3PM",
    about: "Delivers compassionate end‑of‑life care.",
    image: "/images/mb12.jpg",
    job: "Palliative Nurse"
  },
  {
    id: 114,
    name: "Nurse Mehreen Iqbal",
    email: "mehreen.iqbal@clinic.pk",
    specialization: "Public Health Nurse",
    clinic_name: "City Health Department",
    location: "Karachi",
    contact: "+92 301 6667788",
    experience: "11 years",
    department: "BSN",
    qualification: "BSN, RN",
    available_time: "Mon‑Fri, 8AM‑4PM",
    about: "Works on vaccination and community outreach programs.",
    image: "/images/mb14.jpg",
    job: "Public Health Nurse"
  },
  {
    id: 115,
    name: "Nurse Laila Khan",
    email: "laila.khan@clinic.pk",
    specialization: "Informatics Nurse",
    clinic_name: "Health Tech Lab",
    location: "Lahore",
    contact: "+92 302 7778899",
    experience: "5 years",
    department: "BSN",
    qualification: "BSN, RN",
    available_time: "Mon‑Fri, 9AM‑5PM",
    about: "Manages electronic health record systems.",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=870&auto=format&fit=crop",
    job: "Health Informatics Specialist"
  },
  {
    id: 116,
    name: "Nurse Saba Iftikhar",
    email: "saba.iftikhar@clinic.pk",
    specialization: "Flight Nurse",
    clinic_name: "AirMed Services",
    location: "Islamabad",
    contact: "+92 333 8889990",
    experience: "7 years",
    department: "BSN",
    qualification: "BSN, RN",
    available_time: "On‑call shifts",
    about: "Provides in‑flight emergency medical care.",
    image: "/images/mb13.jpg",
    job: "Flight Nurse"
  },
  {
    id: 117,
    name: "Nurse Zainab Mir",
    email: "zainab.mir@clinic.pk",
    specialization: "Legal Nurse Consultant",
    clinic_name: "Legal Health Advisors",
    location: "Karachi",
    contact: "+92 301 9990001",
    experience: "6 years",
    department: "BSN",
    qualification: "BSN, RN",
    available_time: "Mon‑Fri, 8AM‑2PM",
    about: "Reviews medical records for legal cases.",
    image: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?q=80&w=870&auto=format&fit=crop",
    job: "Legal Nurse Consultant"
  },
  {
    id: 118,
    name: "Nurse Yasmin Farooq",
    email: "yasmin.farooq@clinic.pk",
    specialization: "Clinical Nurse Leader",
    clinic_name: "General Hospital",
    location: "Multan",
    contact: "+92 302 1234567",
    experience: "8 years",
    department: "BSN",
    qualification: "BSN, CNL",
    available_time: "Mon‑Fri, 9AM‑5PM",
    about: "Coordinates patient care and nursing teams.",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=870&auto=format&fit=crop",
    job: "Clinical Nurse Leader"
  },
  {
    id: 119,
    name: "Nurse Samra Malik",
    email: "samra.malik@clinic.pk",
    specialization: "Nephrology Nurse",
    clinic_name: "Renal Care Clinic",
    location: "Faisalabad",
    contact: "+92 303 2345678",
    experience: "4 years",
    department: "BSN",
    qualification: "BSN, RN",
    available_time: "Mon‑Sat, 8AM‑2PM",
    about: "Supports dialysis and transplant patients.",
    image: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?q=80&w=870&auto=format&fit=crop",
    job: "Dialysis Coordinator"
  },
  {
    id: 120,
    name: "Nurse Iman Qureshi",
    email: "iman.qureshi@clinic.pk",
    specialization: "Case Management Nurse",
    clinic_name: "HealthCare Trust",
    location: "Peshawar",
    contact: "+92 304 3456789",
    experience: "10 years",
    department: "BSN",
    qualification: "BSN, RN",
    available_time: "Mon-Fri, 9AM-3PM",
    about: "Manages patient cases and discharge planning.",
    image: "/images/mb23.jpg",
    job: "Case Management Nurse"
  },
  {
    id: 121,
    name: "Nurse Rida Hassan",
    email: "rida.hassan@clinic.pk",
    specialization: "Trauma Nurse",
    clinic_name: "Emergency Trauma Center",
    location: "Quetta",
    contact: "+92 305 4567890",
    experience: "8 years",
    department: "BSN",
    qualification: "BSN, TNCC",
    available_time: "Shift-based",
    about: "Handles emergency trauma cases.",
    image: "/images/mb22.jpg",
    job: "Trauma Response Nurse"
  },
  {
    id: 122,
    name: "Nurse Huma Tariq",
    email: "huma.tariq@clinic.pk",
    specialization: "Ambulatory Care Nurse",
    clinic_name: "Outpatient Clinic",
    location: "Lahore",
    contact: "+92 306 5678901",
    experience: "7 years",
    department: "BSN",
    qualification: "BSN, RN",
    available_time: "Mon-Fri, 8AM-4PM",
    about: "Provides outpatient nursing & wound care services.",
    image: "/images/mb21.jpg",
    job: "Ambulatory Nurse"
  },
  // Another Trauma Nurse (same specialization, different experience)
  {
    id: 123,
    name: "Nurse Saad Ahmed",
    email: "saad.ahmed@clinic.pk",
    specialization: "Trauma Nurse",
    clinic_name: "Trauma Response Unit",
    location: "Karachi",
    contact: "+92 300 1122334",
    experience: "4 years",
    department: "BSN",
    qualification: "BSN, TNCC",
    available_time: "Night Shifts",
    about: "Specializes in trauma stabilization.",
    image: "/images/mb18.jpg",
    job: "Trauma Nurse"
  },
  // Another Ambulatory Care Nurse
  {
    id: 124,
    name: "Nurse Bilal Shah",
    email: "bilal.shah@clinic.pk",
    specialization: "Ambulatory Care Nurse",
    clinic_name: "Primary Health Clinic",
    location: "Islamabad",
    contact: "+92 311 2233445",
    experience: "6 years",
    department: "BSN",
    qualification: "BSN, RN",
    available_time: "Mon-Fri, 9AM-5PM",
    about: "Provides wound care and outpatient services.",
    image: "/images/mb25.jpg",
    job: "Ambulatory Nurse"
  },
  // Another Case Management Nurse
  {
    id: 125,
    name: "Nurse Adeel Malik",
    email: "adeel.malik@clinic.pk",
    specialization: "Case Management Nurse",
    clinic_name: "Wellness Hospital",
    location: "Lahore",
    contact: "+92 322 4455667",
    experience: "9 years",
    department: "BSN",
    qualification: "BSN, RN",
    available_time: "Mon-Thu, 10AM-4PM",
    about: "Coordinates patient care and discharge planning.",
    image: "/imagesBsn/bsn1.jpg",
    job: "Case Management Nurse"
  }
];



function generateReviews() {
  const patients = [
    "Hassan Ali", "Zara Khan", "Muneeb Raza", "Sana Tariq", "Ali Hamza",
    "Fariha Noor", "Imran Qureshi", "Laiba Shah", "Noman Ijaz", "Sarah Zubair"
  ];
  const comments = [
    "Excellent care and very professional.",
    "Highly knowledgeable and friendly.",
    "Made me feel comfortable throughout.",
    "Quick diagnosis and effective treatment.",
    "Explained everything clearly and patiently.",
    "Office staff was also helpful.",
    "Would definitely recommend.",
    "Great doctor, very thorough!"
  ];

  return Array.from({ length: 4 }, () => ({
    patient: patients[Math.floor(Math.random() * patients.length)],
    rating: Math.floor(Math.random() * 3) + 3, // 3 to 5
    comment: comments[Math.floor(Math.random() * comments.length)]
  }));
}
