export const doctors = [
  {
    "id": 1,
    "name": "Dr. Ayesha Khan",
    "email": "doctor0@clinic.pk",
    "specialization": "Dermatologist",
    "clinic_name": "Shaafi Medical Center",
    "location": "Shaafi Medical Center, Rawalpindi",
    "contact": "+92 354 1896419",
    "experience": "7 years",
    "department": "MBBS",
    "qualification": "MBBS, FCPS (Dermatology)",
    "available_time": "Mon-Sat, 10AM - 4PM",
    "about": "Dr. Ayesha Khan is a well-experienced dermatologist practicing in Rawalpindi. Known for compassionate care and accurate diagnosis.",
    "image": "https://as1.ftcdn.net/v2/jpg/03/13/77/82/1000_F_313778250_Y0o5can6MA490Nt7G6p03Zfu5fKmWCIv.jpg",
    "job": "Consultant Physician"
  },
  {
    "id": 2,
    "name": "Dr. Ahmed Raza",
    "email": "doctor1@clinic.pk",
    "specialization": "Pediatrician",
    "clinic_name": "City Medical Center",
    "location": "City Medical Center, Quetta",
    "contact": "+92 376 7734279",
    "experience": "12 years",
    "department": "MBBS",
    "qualification": "MBBS, FCPS (Pediatrics)",
    "available_time": "Mon-Sat, 10AM - 4PM",
    "about": "Dr. Ahmed Raza is a well-experienced pediatrician practicing in Quetta. Known for compassionate care and accurate diagnosis.",
    "image": "/images/mb16.jpg",
    "job": "Senior Consultant"
  },
  {
    "id": 3,
    "name": "Dr. Haider Tariq",
    "email": "doctor2@clinic.pk",
    "specialization": "Neurologist",
    "clinic_name": "Madina Town Clinic",
    "location": "Madina Town Clinic, Faisalabad",
    "contact": "+92 361 2461976",
    "experience": "20 years",
    "department": "MBBS",
    "qualification": "MBBS, FCPS (Neurology)",
    "available_time": "Mon-Sat, 10AM - 4PM",
    "about": "Dr. Haider Tariq is a well-experienced neurologist practicing in Faisalabad. Known for compassionate care and accurate diagnosis.",
    "image": "/images/mb24.jpg",
    "job": "Head of Department"
  },
  {
    "id": 4,
    "name": "Dr. Hassan Malik",
    "email": "doctor3@clinic.pk",
    "specialization": "Psychiatrist",
    "clinic_name": "Hayat Medical Complex",
    "location": "Hayat Medical Complex, Peshawar",
    "contact": "+92 374 2435185",
    "experience": "10 years",
    "department": "MBBS",
    "qualification": "MBBS, FCPS (Psychiatry)",
    "available_time": "Mon-Sat, 9AM - 2PM",
    "about": "Dr. Hassan Malik is a well-experienced psychiatrist practicing in Peshawar. Known for compassionate care and accurate diagnosis.",
    "image": "/images/mb1.webp",
    "job": "Resident Medical Officer"
  },
  {
    "id": 5,
    "name": "Dr. Maryam Saeed",
    "email": "doctor4@clinic.pk",
    "specialization": "Oncologist",
    "clinic_name": "Hayat Medical Complex",
    "location": "Hayat Medical Complex, Peshawar",
    "contact": "+92 395 8594912",
    "experience": "13 years",
    "department": "MBBS",
    "qualification": "MBBS, FCPS (Oncology)",
    "available_time": "Mon-Sat, 11AM - 5PM",
    "about": "Dr. Maryam Saeed is a well-experienced oncologist practicing in Peshawar. Known for compassionate care and accurate diagnosis.",
    "image": "/images/mb3.jpg",
    "job": "Clinical Researcher"
  },
  {
    "id": 6,
    "name": "Dr. Bilal Qureshi",
    "email": "doctor5@clinic.pk",
    "specialization": "Oncologist",
    "clinic_name": "Rehman HealthCare",
    "location": "Rehman HealthCare, Sialkot",
    "contact": "+92 315 2894382",
    "experience": "8 years",
    "department": "MBBS",
    "qualification": "MBBS, FCPS (Oncology)",
    "available_time": "Mon-Sat, 9AM - 2PM",
    "about": "Dr. Bilal Qureshi is a well-experienced oncologist practicing in Sialkot. Known for compassionate care and accurate diagnosis.",
    "image": "/images/mb9.jpg",
    "job": "Associate Professor"
  },
  {
    "id": 7,
    "name": "Dr. Noor Fatima",
    "email": "doctor6@clinic.pk",
    "specialization": "Gynecologist",
    "clinic_name": "Hayat Medical Complex",
    "location": "Hayat Medical Complex, Peshawar",
    "contact": "+92 324 7173446",
    "experience": "8 years",
    "department": "MBBS",
    "qualification": "MBBS, FCPS (Gynecology)",
    "available_time": "Mon-Sat, 11AM - 5PM",
    "about": "Dr. Noor Fatima is a well-experienced gynecologist practicing in Peshawar. Known for compassionate care and accurate diagnosis.",
    "image": "/images/mb4.jpg",
    "job": "Medical Officer"
  },
  {
    "id": 8,
    "name": "Dr. Zain Ul Abideen",
    "email": "doctor7@clinic.pk",
    "specialization": "Urologist",
    "clinic_name": "Rehman HealthCare",
    "location": "Rehman HealthCare, Sialkot",
    "contact": "+92 320 6614546",
    "experience": "17 years",
    "department": "MBBS",
    "qualification": "MBBS, FCPS (Urology)",
    "available_time": "Mon-Sat, 10AM - 4PM",
    "about": "Dr. Zain Ul Abideen is a well-experienced urologist practicing in Sialkot. Known for compassionate care and accurate diagnosis.",
    "image": "/images/mb2.jpg",
    "job": "Attending Physician"
  },
  {
    "id": 9,
    "name": "Dr. Mahnoor Shah",
    "email": "doctor8@clinic.pk",
    "specialization": "Dermatologist",
    "clinic_name": "Noor Clinic",
    "location": "Noor Clinic, Lahore",
    "contact": "+92 368 7757403",
    "experience": "6 years",
    "department": "MBBS",
    "qualification": "MBBS, FCPS (Dermatology)",
    "available_time": "Mon-Sat, 9AM - 2PM",
    "about": "Dr. Mahnoor Shah is a well-experienced dermatologist practicing in Lahore. Known for compassionate care and accurate diagnosis.",
    "image": "/images/mb8.jpg",
    "job": "Consulting Specialist"
  },

  {
    "id": 10,
    "name": "Dr. Hamza Ali",
    "email": "doctor9@clinic.pk",
    "specialization": "Dermatologist",
    "clinic_name": "Hayat Medical Complex",
    "location": "Hayat Medical Complex, Peshawar",
    "contact": "+92 312 1280933",
    "experience": "12 years",
     "department": "MBBS",
    "qualification": "MBBS, FCPS (Dermatology)",
    "available_time": "Mon-Sat, 11AM - 5PM",
     "job": "Senior Dermatology Consultant",
    "about": "Dr. Hamza Ali is a well-experienced dermatologist practicing in Peshawar. Known for compassionate care and accurate diagnosis.",
    "image": "/images/mb5.jpg"
  },
  {
    "id": 11,
    "name": "Dr. Anaya Siddiqui",
    "email": "doctor10@clinic.pk",
    "specialization": "Pediatrician",
    "clinic_name": "Al Shifa Hospital",
    "location": "Al Shifa Hospital, Karachi",
    "contact": "+92 353 1056549",
    "experience": "19 years",
     "department": "MBBS",
    "qualification": "MBBS, FCPS (Pediatrics)",
    "available_time": "Mon-Sat, 9AM - 2PM",
     "job": "Senior Pediatric Consultant",
    "about": "Dr. Anaya Siddiqui is a well-experienced pediatrician practicing in Karachi. Known for compassionate care and accurate diagnosis.",
    "image": "/images/mb10.jpg"
  },
  {
    "id": 12,
    "name": "Dr. Usman Ghani",
    "email": "doctor11@clinic.pk",
    "specialization": "ENT Specialist",
    "clinic_name": "Madina Town Clinic",
    "location": "Madina Town Clinic, Faisalabad",
    "contact": "+92 369 3787576",
    "experience": "10 years",
     "department": "MBBS",
    "qualification": "MBBS, FCPS (ENT)",
    "available_time": "Mon-Sat, 10AM - 4PM",
    "job": "Senior ENT Consultant",
    "about": "Dr. Usman Ghani is a well-experienced ent specialist practicing in Faisalabad. Known for compassionate care and accurate diagnosis.",
    "image": "/images/mb6.jpg"
  },
  {
    "id": 13,
    "name": "Dr. Huda Imran",
    "email": "doctor12@clinic.pk",
    "specialization": "ENT Specialist",
    "clinic_name": "Sir Syed Clinic",
    "location": "Sir Syed Clinic, Hyderabad",
    "contact": "+92 398 3594553",
     "department": "MBBS",
    "experience": "12 years",
    "qualification": "MBBS, FCPS (ENT)",
    "available_time": "Mon-Sat, 10AM - 4PM",
     "job": "Senior ENT Consultant",
    "about": "Dr. Huda Imran is a well-experienced ent specialist practicing in Hyderabad. Known for compassionate care and accurate diagnosis.",
    "image": "/images/mb11.jpg"
  },
  {
    "id": 14,
    "name": "Dr. Salman Qadri",
    "email": "doctor13@clinic.pk",
    "specialization": "Oncologist",
    "clinic_name": "Madina Town Clinic",
    "location": "Madina Town Clinic, Faisalabad",
    "contact": "+92 378 5380544",
    "experience": "7 years",
     "department": "MBBS",
    "qualification": "MBBS, FCPS (Oncology)",
    "available_time": "Mon-Sat, 11AM - 5PM",
    "job": "Senior Oncology Consultant",
    "about": "Dr. Salman Qadri is a well-experienced oncologist practicing in Faisalabad. Known for compassionate care and accurate diagnosis.",
    "image": "/images/mb7.jpg"
  },
  {
    "id": 15,
    "name": "Dr. Sana Batool",
    "email": "doctor14@clinic.pk",
    "specialization": "Cardiologist",
    "clinic_name": "Nishtar Specialist Clinic",
    "location": "Nishtar Specialist Clinic, Multan",
    "contact": "+92 364 1156281",
    "experience": "6 years",
     "department": "MBBS",
    "qualification": "MBBS, FCPS (Cardiology)",
    "available_time": "Mon-Sat, 9AM - 2PM",
    "about": "Dr. Sana Batool is a well-experienced cardiologist practicing in Multan. Known for compassionate care and accurate diagnosis.",
    "job": "Senior Cardiology Consultant",
    "image": "/images/mb12.jpg"
  },
  {
    "id": 16,
    "name": "Dr. Faisal Farooq",
    "email": "doctor15@clinic.pk",
    "specialization": "Orthopedic Surgeon",
    "clinic_name": "Rehman HealthCare",
    "location": "Rehman HealthCare, Sialkot",
    "contact": "+92 329 2042890",
    "experience": "10 years",
     "department": "MBBS",
    "qualification": "MBBS, MS (Orthopedics)",
    "available_time": "Mon-Sat, 10AM - 4PM",
    "about": "Dr. Faisal Farooq is a well-experienced orthopedic surgeon practicing in Sialkot. Known for compassionate care and accurate diagnosis.",
     "job":     "Consultant Orthopedic Surgeon",
    "image": "/images/mb12.jpg"
  },
  {
    "id": 17,
    "name": "Dr. Iqra Zahid",
    "email": "doctor16@clinic.pk",
    "specialization": "Orthopedic Surgeon",
    "clinic_name": "Rehman HealthCare",
    "location": "Rehman HealthCare, Sialkot",
    "contact": "+92 318 1153298",
    "experience": "16 years",
     "department": "MBBS",
    "qualification": "MBBS, MS (Orthopedics)",
    "available_time": "Mon-Sat, 10AM - 4PM",
    "about": "Dr. Iqra Zahid is a well-experienced orthopedic surgeon practicing in Sialkot. Known for compassionate care and accurate diagnosis.",
     "job": "Consultant Orthopedic Surgeon",
    "image": "/images/mb13.jpg"
  },
  {
    "id": 18,
    "name": "Dr. Yousuf Shahid",
    "email": "doctor17@clinic.pk",
    "specialization": "Gynecologist",
    "clinic_name": "Shaafi Medical Center",
    "location": "Shaafi Medical Center, Rawalpindi",
    "contact": "+92 365 3898208",
    "experience": "15 years",
     "department": "MBBS",
    "qualification": "MBBS, FCPS (Gynecology)",
    "available_time": "Mon-Sat, 11AM - 5PM",
    "about": "Dr. Yousuf Shahid is a well-experienced gynecologist practicing in Rawalpindi. Known for compassionate care and accurate diagnosis.",
    "job": "Senior Gynecology Consultant",
    "image": "/images/mb15.jpg"
  },
  {
    "id": 19,
    "name": "Dr.  Hashir Ahmad",
    "email": "doctor18@clinic.pk",
    "specialization": "Dermatologist",
    "clinic_name": "City Medical Center",
    "location": "City Medical Center, Quetta",
    "contact": "+92 345 4590877",
    "experience": "9 years",
     "department": "MBBS",
    "qualification": "MBBS, FCPS (Dermatology)",
    "available_time": "Mon-Sat, 10AM - 4PM",
    "about": "Dr. Laiba Noman is a well-experienced dermatologist practicing in Quetta. Known for compassionate care and accurate diagnosis.",
    "job": "Senior Dermatology Consultant",
    "image": "https://as2.ftcdn.net/v2/jpg/02/60/04/09/1000_F_260040900_oO6YW1sHTnKxby4GcjCvtypUCWjnQRg5.jpg"
  },
  {
    "id": 20,
    "name": "Dr. Ibrahim Danish",
    "email": "doctor19@clinic.pk",
    "specialization": "Cardiologist",
    "clinic_name": "Al Shifa Hospital",
    "location": "Al Shifa Hospital, Karachi",
    "contact": "+92 353 3393527",
    "experience": "20 years",
     "department": "MBBS",
    "qualification": "MBBS, FCPS (Cardiology)",
    "available_time": "Mon-Sat, 9AM - 2PM",
    "about": "Dr. Ibrahim Danish is a well-experienced cardiologist practicing in Karachi. Known for compassionate care and accurate diagnosis.",
    "job": "Senior Cardiology Consultant",
    "image": "/images/mb17.jpg"
  },
  {
    "id": 21,
    "name": "Dr. Umer Jameel",
    "email": "doctor20@clinic.pk",
    "specialization": "Gynecologist",
    "clinic_name": "Madina Town Clinic",
    "location": "Madina Town Clinic, Faisalabad",
    "contact": "+92 345 6221495",
    "experience": "13 years",
     "department": "MBBS",
    "qualification": "MBBS, FCPS (Gynecology)",
    "available_time": "Mon-Sat, 9AM - 2PM",
    "about": "Dr. Umer Jameel is a well-experienced gynecologist practicing in Faisalabad. Known for compassionate care and accurate diagnosis.",
    "job": "Senior Gynecology Consultant",
    "image": "/images/mb25.jpg"
  },
  {
    "id": 22,
    "name": "Dr. Rameen Khalid",
    "email": "doctor21@clinic.pk",
    "specialization": "Oncologist",
    "clinic_name": "HealthCare Plus Center",
    "location": "HealthCare Plus Center, Islamabad",
    "contact": "+92 348 4616577",
    "experience": "18 years",
     "department": "MBBS",
    "qualification": "MBBS, FCPS (Oncology)",
    "available_time": "Mon-Sat, 10AM - 4PM",
    "about": "Dr. Rameen Khalid is a well-experienced oncologist practicing in Islamabad. Known for compassionate care and accurate diagnosis.",
    "job": "Senior Oncology Consultant",
    "image": "/images/mb23.jpg"
  },
  {
    "id": 23,
    "name": "Dr. Saif Ur Rehman",
    "email": "doctor22@clinic.pk",
    "specialization": "Urologist",
    "clinic_name": "Al Shifa Hospital",
    "location": "Al Shifa Hospital, Karachi",
    "contact": "+92 373 9776788",
    "experience": "11 years",
     "department": "MBBS",
    "qualification": "MBBS, FCPS (Urology)",
    "available_time": "Mon-Sat, 10AM - 4PM",
    "about": "Dr. Saif Ur Rehman is a well-experienced urologist practicing in Karachi. Known for compassionate care and accurate diagnosis.",
     "job": "Senior Urology Consultant",
    "image": "/images/mb19.jpg"
  },
  {
    "id": 24,
    "name": "Dr. Maham Junaid",
    "email": "doctor23@clinic.pk",
    "specialization": "Neurologist",
    "clinic_name": "Madina Town Clinic",
    "location": "Madina Town Clinic, Faisalabad",
    "contact": "+92 379 3889307",
    "experience": "15 years",
     "department": "MBBS",
    "qualification": "MBBS, FCPS (Neurology)",
    "available_time": "Mon-Sat, 10AM - 4PM",
    "about": "Dr. Maham Junaid is a well-experienced neurologist practicing in Faisalabad. Known for compassionate care and accurate diagnosis.",
     "job": "Consultant Neurologist",
    "image": "/images/mb22.jpg"
  },
  {
    "id": 25,
    "name": "Dr. Talha Saeed",
    "email": "doctor24@clinic.pk",
    "specialization": "Orthopedic Surgeon",
    "clinic_name": "Noor Clinic",
    "location": "Noor Clinic, Lahore",
    "contact": "+92 387 3938016",
    "experience": "9 years",
     "department": "MBBS",
    "qualification": "MBBS, MS (Orthopedics)",
    "available_time": "Mon-Sat, 11AM - 5PM",
    "about": "Dr. Talha Saeed is a well-experienced orthopedic surgeon practicing in Lahore. Known for compassionate care and accurate diagnosis.",
    "job": "Senior Orthopedic Consultant",
    "image": "/images/mb20.jpg"
  },
  {
    "id": 26,
    "name": "Dr. Alina Rehman",
    "email": "doctor25@clinic.pk",
    "specialization": "Cardiologist",
    "clinic_name": "Al Shifa Hospital",
    "location": "Al Shifa Hospital, Karachi",
    "contact": "+92 333 6779412",
    "experience": "5 years",
     "department": "MBBS",
    "qualification": "MBBS, FCPS (Cardiology)",
    "available_time": "Mon-Sat, 9AM - 2PM",
    "about": "Dr. Alina Rehman is a well-experienced cardiologist practicing in Karachi. Known for compassionate care and accurate diagnosis.",

 "job": "Consultant Cardiologist",


    "image": "/images/mb21.jpg"



  },
  {
    "id": 27,
    "name": "Dr. Farhan Mehmood",
    "email": "doctor26@clinic.pk",
    "specialization": "Gynecologist",
    "clinic_name": "Al Shifa Hospital",
    "location": "Al Shifa Hospital, Karachi",
    "contact": "+92 312 1354147",
    "experience": "18 years",
     "department": "MBBS",
    "qualification": "MBBS, FCPS (Gynecology)",
    "available_time": "Mon-Sat, 11AM - 5PM",
    "about": "Dr. Farhan Mehmood is a well-experienced gynecologist practicing in Karachi. Known for compassionate care and accurate diagnosis.",
      "job": "Medical Advisor",
    "image": "/images/mb18.jpg"
  }
]

export default doctors;

function generateEmail(name) {
  return name.toLowerCase().replace("dr. ", "").replace(/\s+/g, "") + "@clinic.pk";
}

function generateReviews() {
  const patients = [
    "Hassan Ali", "Zara Khan", "Muneeb Raza", "Sana Tariq", "Ali Hamza",
    "Fariha Noor", "Imran Qureshi", "Laiba Shah", "Noman Ijaz", "Sarah Zubair"
  ];
  const comments = [
    "Excellent care and very professional.",
    "Highly knowledgeable and friendly.",
    "Made me feel comfortable throughout.",
    "Quick diagnosis and effective treatment.",
    "Explained everything clearly and patiently.",
    "Office staff was also helpful.",
    "Would definitely recommend.",
    "Great doctor, very thorough!"
  ];

  return Array.from({ length: 4 }, () => ({
    patient: patients[Math.floor(Math.random() * patients.length)],
    rating: Math.floor(Math.random() * 3) + 3, // 3 to 5
    comment: comments[Math.floor(Math.random() * comments.length)]
  }));
}

// Apply to all doctors
doctors.forEach(doc => {
  doc.email = generateEmail(doc.name);
  doc.reviews = generateReviews();
});

console.log(doctors);


